version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: googleapis
    versions:
    - 67.1.1
    - 68.0.0
    - 71.0.0
    - 72.0.0
  - dependency-name: node-html-parser
    versions:
    - 3.0.4
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.1.4
    - 3.1.5
    - 3.1.6
  - dependency-name: markdown-it
    versions:
    - 12.0.5
  - dependency-name: crypto-random-string
    versions:
    - 4.0.0
  - dependency-name: bcrypt
    versions:
    - 5.0.1
  - dependency-name: apollo-server-express
    versions:
    - 2.21.1
    - 2.21.2
    - 2.22.0
    - 2.22.1
  - dependency-name: sequelize
    versions:
    - 6.5.1
    - 6.6.1
  - dependency-name: open-graph-scraper
    versions:
    - 4.8.1
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.3.1
    - 4.3.3
  - dependency-name: google-auth-library
    versions:
    - 7.0.1
