pull_request_rules:
  - name: automatic merge of bot 🤖 (low priority)
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Node.js CI / build-on-postgres (14.x, ubuntu-20.04) (push)
      - base=master
    actions:
      merge:
        method: merge
        strict: smart
        priority: low