version: 2.1
orbs:
    node: circleci/node@1.1.6
commands:
    check-port-listening:
        parameters:
            port:
                type: string
                default: "3306"
        steps:
            - run:
                  # Our primary container isn't MYSQL so run a sleep command until it's ready.
                  name: Waiting for port to start listening
                  command: |
                      for i in `seq 1 10`;
                      do
                        npx is-port-listening --port=<< parameters.port >> && echo Success && exit 0
                        echo -n .
                        sleep 2
                      done
                      echo Failed waiting for MySQL && exit 1
jobs:
    mysql:
        environment:
            SEQUELIZE_URL: mysql://root:password@localhost:3306/ci
            COVERALLS_GIT_BRANCH: ${ CIRCLE_BRANCH }
        executor:
            name: node/default
        docker:
            - image: node:14.7.0
            - image: circleci/mysql:5.7
              environment:
                  MYSQL_DATABASE: ci
                  MYSQL_ROOT_PASSWORD: password

        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - check-port-listening:
                            port: "3306"
                      - run: npm run build
                      - run: npm run test
                      - run: npm run coverage
    sqlite:
        executor:
            name: node/default
        docker:
            - image: node:14.7.0
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - run: npm install sqlite3
                      - run: npm run build
                      - run: npm test
workflows:
    build-and-test:
        jobs:
            - mysql
            - sqlite